import type { ArtifactLifecyclePhase } from '@/lib/artifact-lifecycle'

/** Fallback phase lookup by template name when API omits lifecycle_phase. */
export const ARTIFACT_NAME_TO_PHASE: Record<string, ArtifactLifecyclePhase> = {
  'Bid Scope Summary': 'pursuit_bid',
  'RFQ / RFP Requirements Extract': 'pursuit_bid',
  'Cost & Pricing Risks': 'pursuit_bid',
  'Bid Clarification Log': 'pursuit_bid',
  'Competitor / Market Context Brief': 'pursuit_bid',
  'Allowance & Alternate Matrix': 'pursuit_bid',
  'Insurance & Bonding Summary': 'pursuit_bid',
  'Drawing Set Index': 'pursuit_bid',
  'Scope by Drawing Package': 'pursuit_bid',
  'Design Intent Summary': 'pursuit_bid',
  'Quantity Takeoff Extract': 'precon',
  'Schedule & Milestones': 'precon',
  'Submittal / Spec Compliance': 'precon',
  'Spec Section Digest': 'precon',
  'Drawing–Spec Crosswalk': 'precon',
  'Coordination Conflict Scan': 'precon',
  'Long-Lead Item Register': 'precon',
  'Permit & Inspection Roadmap': 'precon',
  'Value Engineering Opportunities': 'precon',
  'Room / Area Program': 'precon',
  'Door & Window Schedule Extract': 'precon',
  'Finish Schedule Extract': 'precon',
  'Accessibility (ADA) Checklist': 'precon',
  'Life Safety / Egress Summary': 'precon',
  'Structural Notes Digest': 'precon',
  'Site & Civil Summary': 'precon',
  'Subcontractor Scope Letter Draft': 'mobilization',
  'Site Logistics Plan Brief': 'mobilization',
  'Procurement Tracker Seed': 'mobilization',
  'Preconstruction Meeting Brief': 'mobilization',
  'Baseline Schedule Narrative': 'mobilization',
  'Change-Order Impact': 'construction',
  'Safety & Code Checklist': 'construction',
  'RFI Draft / Register Entry': 'construction',
  'Submittal Review Summary': 'construction',
  'Daily Report Digest': 'construction',
  'Punch List Item Extract': 'construction',
  'Progress vs Schedule Snapshot': 'construction',
  'Meeting Minutes (Construction)': 'construction',
  'Delay & Claim Evidence Pack': 'construction',
  'Quality Control Checklist': 'construction',
  'Revision Delta Summary': 'construction',
  'As-Built Markup Guide': 'construction',
  'Installation Sequence by Area': 'construction',
  'Closeout Document Checklist': 'closeout',
  'O&M Manual Index': 'closeout',
  'Warranty Register': 'closeout',
  'Training & Turnover Brief': 'closeout',
  'Final Punch by Trade': 'closeout',
  'Lessons Learned Report': 'closeout',
  'Project Executive Summary': 'closeout',
  'Project Risk Register': 'cross_cutting',
  'Open Items Dashboard': 'cross_cutting',
  'Trade Responsibility Matrix': 'cross_cutting',
  'Document Conflict Report': 'cross_cutting',
  'Owner / GC Communication Log': 'cross_cutting',
  'Constructability Review': 'cross_cutting',
}
